language: c
compiler: gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq apt-transport-https
    - echo "deb https://kdudka.fedorapeople.org/csbuild precise contrib" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq -y --force-yes automake csbuild
    - sudo apt-get install libssl-dev libtool

script:
    - test -z "$TRAVIS_COMMIT_RANGE" || csbuild --git-commit-range "$TRAVIS_COMMIT_RANGE" -c "./buildconf && ./configure --with-openssl --quiet && make -s clean && make -j9 V=0" --git-bisect --print-fixed
